run_name: d2_energy_model_AR_full
dtype: float32

# Data
hdf5_file: /project/biocomplexity/fa7sa/calochallenge_datasets/dataset_2/dataset_2_1.hdf5
eval_hdf5_file: /project/biocomplexity/fa7sa/calochallenge_datasets/dataset_2/dataset_2_2.hdf5
xml_filename: /project/biocomplexity/fa7sa/calo_dreamer/src/challenge_files/binning_dataset_2.xml
val_frac: 0.00001
eps: 1.0e-10
particle_type: electron
eval_dataset: "2"
shape: [45]

# Preprocessing
transforms:
    #ScaleVoxels:
    #    factor: 0.35
    NormalizeByElayer:
        ptype: /remote/gpu02/ore/calo_dreamer/src/challenge_files/binning_dataset_2.xml
        xml_file: electron
    ScaleTotalEnergy: 
        factor: 0.35
    SelectDims:
        start: -45
        end: 0
    ExclusiveLogitTransform:
        delta: 1.0e-6
        rescale: True
    StandardizeFromFile: {}
    LogEnergy: {}
    ScaleEnergy:
        e_min: 6.907755
        e_max: 13.815510
    Reshape:
        shape: [45, 1]
        
batch_size: 128

# Model for energytransformer
model_type: energy
#model: TransfusionAR
#network: ARtransformer
shape: [45] # number of calorimeter layers
dim_embedding: 64
n_head: 4
n_encoder_layers: 4
n_decoder_layers: 4
dim_feedforward: 512
#encode_c_dim: 64
n_con: 1
conditional: True
#c_embed: True
#x_embed: True
#conditional: True
#encode_t: True
#encode_t_dim: 64
#encode_c: True
normalization: LayerNorm

#arguments for Diffusion for energy network
emd_dim: 64 # time and conditional embedding size
lr: 1.e-3
max_lr: 2.e-3
epochs: 50



#validation
do_validation: True


#sampling
n_samples: 1000
batch_size_sample: 1000
sample_time: 363.46789836883545